kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc

spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      tier: mysql