kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  labels:
    tier: mysql
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/mysql/"